Iter13
ramil063/gometrics pull request #13
Opened 2024-12-11 19:53 UTC by ramil063

2024-12-12 19:34 UTC, avhitrov requested changes
Гонки на сторадже, практически отсутствует работа с ошибками, не работает агент и много прочих замечаний. В комментариях к коду.

2024-12-12 19:34 UTC, avhitrov commented on cmd/agent/handlers/request.go
> +func (r request) SendMultipleMetricsJSON(c JSONClienter, maxCount int) error {
Функция при любом раскладе рапортует наверх о том, что все прошло без ошибок. Очевидно, что это не совсем верное поведение, особенно в разрезе необходимости сброса счетчика при успешной отправке и не-сброса при неуспешной.

Нигде в задании не указано, что агент должен сработать ограниченное количество раз. Более того, стандартный алгоритм работы систем мониторинга предполагает, что агент работает столь долго, сколько вообще возможно, обходя все возможности падения.

2024-12-12 19:34 UTC, avhitrov commented on cmd/server/storage/file/file.go
> +	metrics.Counters[name] += value
Мапа – структура потоконебезопасная. Это означает, что в конкурентной среде (а http-сервер априори является конкурентным приложением, так как открывает по горутине на каждый входящий запрос) любые обращения к ней должны оборачиваться блокировками. В Go для этого существуют мьютексы (sync.Mutex или sync.RWMutex). Кроме того, можно использовать потокозащищенные структуры, вроде sync.Map.

Подробнее: https://t.me/bushigo/24

В данном же случае при множестве одновременных запросов имеем (аналогично и для файлового, и для in-memory хранилища):
```
==================
WARNING: DATA RACE
Write at 0x00c00002b260 by goroutine 108:
  runtime.mapassign_faststr()
      C:/Apps/Go/src/runtime/map_faststr.go:223 +0x0
  github.com/ramil063/gometrics/cmd/server/storage/memory.(*MemStorage).SetGauge()
      C:/work/src/github.com/ramil063/gometrics/cmd/server/storage/memory/memory.go:13 +0x56
  github.com/ramil063/gometrics/cmd/server/handlers/server.updateMetricsJSON()
      C:/work/src/github.com/ramil063/gometrics/cmd/server/handlers/server/server.go:199 +0x6f6
  github.com/ramil063/gometrics/cmd/server/handlers/server.Router.func2.2()
      C:/work/src/github.com/ramil063/gometrics/cmd/server/handlers/server/server.go:63 +0x56
  net/http.HandlerFunc.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:2220 +0x47
  github.com/ramil063/gometrics/cmd/server/handlers/middlewares.CheckPostMethodMw.func1()
      C:/work/src/github.com/ramil063/gometrics/cmd/server/handlers/middlewares/middlewares.go:37 +0x2c5
  net/http.HandlerFunc.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:2220 +0x47
  github.com/go-chi/chi/v5.(*ChainHandler).ServeHTTP()
      c:/work/pkg/mod/github.com/go-chi/chi/v5@v5.1.0/chain.go:31 +0x63
  github.com/go-chi/chi/v5.(*Mux).routeHTTP()
      c:/work/pkg/mod/github.com/go-chi/chi/v5@v5.1.0/mux.go:459 +0x594
  github.com/go-chi/chi/v5.(*Mux).routeHTTP-fm()
      <autogenerated>:1 +0x51
  net/http.HandlerFunc.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:2220 +0x47
  github.com/go-chi/chi/v5.(*Mux).ServeHTTP()
      c:/work/pkg/mod/github.com/go-chi/chi/v5@v5.1.0/mux.go:73 +0x716
  github.com/go-chi/chi/v5.(*Mux).Mount.func1()
      c:/work/pkg/mod/github.com/go-chi/chi/v5@v5.1.0/mux.go:327 +0x4e5
  net/http.HandlerFunc.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:2220 +0x47
  github.com/go-chi/chi/v5.(*Mux).routeHTTP()
      c:/work/pkg/mod/github.com/go-chi/chi/v5@v5.1.0/mux.go:459 +0x594
  github.com/go-chi/chi/v5.(*Mux).routeHTTP-fm()
      <autogenerated>:1 +0x51
  net/http.HandlerFunc.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:2220 +0x47
  github.com/ramil063/gometrics/cmd/server/handlers/middlewares.CheckMethodMw.func1()
      C:/work/src/github.com/ramil063/gometrics/cmd/server/handlers/middlewares/middlewares.go:23 +0x221
  net/http.HandlerFunc.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:2220 +0x47
  github.com/ramil063/gometrics/cmd/server/handlers/middlewares.GZIPMiddleware.func1()
      C:/work/src/github.com/ramil063/gometrics/cmd/server/handlers/middlewares/middlewares.go:185 +0x3e8
  net/http.HandlerFunc.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:2220 +0x47
  github.com/ramil063/gometrics/internal/logger.RequestLogger.func1()
      C:/work/src/github.com/ramil063/gometrics/internal/logger/request.go:36 +0x98
  net/http.HandlerFunc.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:2220 +0x47
  github.com/ramil063/gometrics/internal/logger.ResponseLogger.func1()
      C:/work/src/github.com/ramil063/gometrics/internal/logger/response.go:49 +0x181
  net/http.HandlerFunc.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:2220 +0x47
  github.com/go-chi/chi/v5.(*Mux).ServeHTTP()
      c:/work/pkg/mod/github.com/go-chi/chi/v5@v5.1.0/mux.go:90 +0x69e
  net/http.serverHandler.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:3210 +0x2a1
  net/http.(*conn).serve()
      C:/Apps/Go/src/net/http/server.go:2092 +0x12a4
  net/http.(*Server).Serve.gowrap3()
      C:/Apps/Go/src/net/http/server.go:3360 +0x4f

Previous read at 0x00c00002b260 by goroutine 9:
  runtime.mapiterinit()
      C:/Apps/Go/src/runtime/map.go:877 +0x0
  github.com/ramil063/gometrics/cmd/server/handlers/server.home()
      C:/work/src/github.com/ramil063/gometrics/cmd/server/handlers/server/server.go:147 +0x2c9
  github.com/ramil063/gometrics/cmd/server/handlers/server.Router.func1()
      C:/work/src/github.com/ramil063/gometrics/cmd/server/handlers/server/server.go:47 +0x56
  net/http.HandlerFunc.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:2220 +0x47
  github.com/go-chi/chi/v5.(*Mux).routeHTTP()
      c:/work/pkg/mod/github.com/go-chi/chi/v5@v5.1.0/mux.go:459 +0x594
  github.com/go-chi/chi/v5.(*Mux).routeHTTP-fm()
      <autogenerated>:1 +0x51
  net/http.HandlerFunc.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:2220 +0x47
  github.com/ramil063/gometrics/cmd/server/handlers/middlewares.CheckMethodMw.func1()
      C:/work/src/github.com/ramil063/gometrics/cmd/server/handlers/middlewares/middlewares.go:23 +0x221
  net/http.HandlerFunc.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:2220 +0x47
  github.com/ramil063/gometrics/cmd/server/handlers/middlewares.GZIPMiddleware.func1()
      C:/work/src/github.com/ramil063/gometrics/cmd/server/handlers/middlewares/middlewares.go:185 +0x3e8
  net/http.HandlerFunc.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:2220 +0x47
  github.com/ramil063/gometrics/internal/logger.RequestLogger.func1()
      C:/work/src/github.com/ramil063/gometrics/internal/logger/request.go:36 +0x98
  net/http.HandlerFunc.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:2220 +0x47
  github.com/ramil063/gometrics/internal/logger.ResponseLogger.func1()
      C:/work/src/github.com/ramil063/gometrics/internal/logger/response.go:49 +0x181
  net/http.HandlerFunc.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:2220 +0x47
  github.com/go-chi/chi/v5.(*Mux).ServeHTTP()
      c:/work/pkg/mod/github.com/go-chi/chi/v5@v5.1.0/mux.go:90 +0x69e
  net/http.serverHandler.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:3210 +0x2a1
  net/http.(*conn).serve()
      C:/Apps/Go/src/net/http/server.go:2092 +0x12a4
  net/http.(*Server).Serve.gowrap3()
      C:/Apps/Go/src/net/http/server.go:3360 +0x4f

Goroutine 108 (running) created at:
  net/http.(*Server).Serve()
      C:/Apps/Go/src/net/http/server.go:3360 +0x8ec
  net/http.(*Server).ListenAndServe()
      C:/Apps/Go/src/net/http/server.go:3259 +0xbc
  net/http.ListenAndServe()
      C:/Apps/Go/src/net/http/server.go:3514 +0x54d
  main.main()
      C:/work/src/github.com/ramil063/gometrics/cmd/server/main.go:29 +0x3d1

Goroutine 9 (running) created at:
  net/http.(*Server).Serve()
      C:/Apps/Go/src/net/http/server.go:3360 +0x8ec
  net/http.(*Server).ListenAndServe()
      C:/Apps/Go/src/net/http/server.go:3259 +0xbc
  net/http.ListenAndServe()
      C:/Apps/Go/src/net/http/server.go:3514 +0x54d
  main.main()
      C:/work/src/github.com/ramil063/gometrics/cmd/server/main.go:29 +0x3d1
==================

2024-12-12 19:34 UTC, avhitrov commented on cmd/server/storage/db/get_data.go
> +func (s *Storage) GetGauge(name string) (float64, bool) {
```suggestion
func (s *Storage) GetGauge(name string) (float64, error) {
```
Всегда необходимо возвращать ошибку, а не факт ее наличия или отсутствия. Кроме того, в случае со Scan необходимо анализировать тип ошибки, так как Scan генерит ошибку в том числе в случае ненахождения искомой записи.

2024-12-12 19:34 UTC, avhitrov commented on cmd/server/storage/db/get_data.go
> +func (s *Storage) GetGauges() map[string]models.Gauge {
```suggestion
func (s *Storage) GetGauges() (map[string]models.Gauge, error) {
```

2024-12-12 19:34 UTC, avhitrov commented on cmd/server/storage/db/get_data.go
> +func (s *Storage) GetCounter(name string) (int64, bool) {
```suggestion
func (s *Storage) GetCounter(name string) (int64, error) {
```

2024-12-12 19:34 UTC, avhitrov commented on cmd/server/storage/db/get_data.go
> +func (s *Storage) GetCounters() map[string]models.Counter {
```suggestion
func (s *Storage) GetCounters() (map[string]models.Counter, error) {
```

2024-12-12 19:34 UTC, avhitrov commented on cmd/server/storage/db/dml/repository.go
> +	_ = row.Scan(&selectedName)
```suggestion
	err = row.Scan(&selectedName)
```
О том, что строка не найдена можно узнать ТОЛЬКО из анализа типа ошибки. Потому что отсутствие соединения с БД точно так же вернет пустую selectedName.

А вообще в постгресе для апсертов есть прекрасная конструкция:
```
INSERT INTO counter (name, value) VALUES ($1, $2)
ON CONFLICT (name) SET value = value + $2
```
Только исключительный индекс надо на поле name поставить.

2024-12-12 19:34 UTC, avhitrov commented on cmd/server/storage/db/dml/repository.go
> +func NewRepository() *Repository {
```suggestion
func NewRepository() (*Repository, error) {
```

2024-12-12 19:34 UTC, avhitrov commented on cmd/server/storage/db/db.go
> +	Counters map[string]models.Counter
Зачем они здесь? Писать и читать надо напрямую в БД.

2024-12-12 19:34 UTC, avhitrov commented on cmd/server/main.go
>  	ticker := time.NewTicker(time.Duration(handlers.StoreInterval) * time.Second)
1. Если StoreInterval указать равным нулю или отрицательному числу, система упадет по панике
2. Если мы проинициализировали БД, то этот тикер нам вообще не нужен.

2024-12-12 19:34 UTC, avhitrov commented on cmd/server/storage/db/change_data.go
> +func (s *Storage) AddCounter(name string, value models.Counter) {
```suggestion
func (s *Storage) AddCounter(name string, value models.Counter) error {
```

2024-12-12 19:34 UTC, avhitrov commented on cmd/server/storage/db/change_data.go
> +func (s *Storage) SetGauge(name string, value models.Gauge) {
```suggestion
func (s *Storage) SetGauge(name string, value models.Gauge) error {
```

2024-12-27 20:21 UTC, ramil063 commented on cmd/agent/handlers/request.go
> +func (r request) SendMultipleMetricsJSON(c JSONClienter, maxCount int) error {
сделал правки внутри функции

2025-01-03 13:17 UTC, avhitrov requested changes
Замечания обработаны. Осталось добавить реакции хендлеров на прилетающие ошибки и еще пару моментов, отмеченных в комментариях к коду.

2025-01-03 13:17 UTC, avhitrov commented on cmd/server/main.go
> +	if handlers.Restore && handlers.StoreInterval > 0 {
```suggestion
	if handlers.StoreInterval > 0 && writingToFileIsEnabledAndAvailable {
```
Периодическое сохранение никак не связано с функционалом подгрузки содержимого файла в память при запуске. Оно зависит только от флагов `-f` и `-i` (ну и соответствующих переменных окружения).

2025-01-03 13:17 UTC, avhitrov commented on cmd/server/handlers/server/metrics.go
> +				logger.WriteErrorLog(err.Error(), "Counter")
```suggestion
				logger.WriteErrorLog(err.Error(), "Counter")
				return err
```

2025-01-03 13:17 UTC, avhitrov commented on cmd/server/handlers/server/metrics.go
> +				logger.WriteErrorLog(err.Error(), "Gauge")
```suggestion
				logger.WriteErrorLog(err.Error(), "Gauge")
				return err
```
Если есть возможность поймать и отправить ошибку наверх, необходимо поймать и отправить. Тем более, что данная функция, в частности, дергается внутри хендлера и при наличии ошибки должна честно выдавать клиенту 500.

2025-01-03 13:17 UTC, avhitrov commented on cmd/server/handlers/server/server.go
> +			logger.WriteErrorLog(err.Error(), "Gauge")
Необходимо выставить 500 и выйти.

2025-01-03 13:17 UTC, avhitrov commented on cmd/server/handlers/server/server.go
> +			logger.WriteErrorLog(err.Error(), "Counter")
Необходимо выставить 500 и выйти

2025-01-03 13:17 UTC, avhitrov commented on cmd/server/handlers/server/server.go
> +		logger.WriteErrorLog(err.Error(), "Gauge")
500 и выход

2025-01-03 13:17 UTC, avhitrov commented on cmd/server/handlers/server/server.go
> +		logger.WriteErrorLog(err.Error(), "GetCounters")
500 и выход

2025-01-03 13:17 UTC, avhitrov commented on cmd/server/handlers/server/server.go
> +			logger.WriteErrorLog(err.Error(), "SetGauge")
500 и выйти. И так везде, где можно выставить статус. Там, где уже выставлен (ошибка io.Write), там только логировать.

2025-01-03 13:17 UTC, avhitrov commented on cmd/server/handlers/server/server.go
> +				logger.WriteInfoLog(err.Error(), "SetGauge ID:"+metrics.ID)
500 и выйти

2025-01-03 13:17 UTC, avhitrov commented on cmd/server/handlers/server/server.go
> +			logger.WriteInfoLog(err.Error(), "AddCounter ID:"+metrics.ID)
500 и выйти

2025-01-03 13:17 UTC, avhitrov commented on cmd/server/handlers/server/server.go
> +			logger.WriteInfoLog(err.Error(), "GetCounter ID:"+metrics.ID)
500 и выйти (или, ситуативно 404, если есть возможность проанализировать ошибку)

2025-01-03 13:17 UTC, avhitrov commented on cmd/server/handlers/server/server.go
> +				logger.WriteErrorLog(err.Error(), "SetGauge ID:"+m.ID)
500 и выйти

2025-01-03 13:17 UTC, avhitrov commented on cmd/server/handlers/server/server.go
> +				logger.WriteErrorLog(err.Error(), "AddCounter ID:"+m.ID)
500 и выйти

2025-01-03 13:17 UTC, avhitrov commented on cmd/server/handlers/server/server.go
> +				logger.WriteErrorLog(err.Error(), "GetCounter ID:"+m.ID)
500 и выйти

2025-01-07 21:38 UTC, avhitrov approved these changes
Замечания исправлены, аппрув!

2025-01-08 15:56 UTC, merged