Iter5
ramil063/gometrics pull request #5
Opened 2024-10-06 20:17 UTC by ramil063

2024-10-07 17:25 UTC, rktkov requested changes

2024-10-07 17:25 UTC, rktkov commented on cmd/server/storage/storage.go
> +type MemStorageInterface interface {
Объявление интерфейса переносим в место, где он используется, а не реализуется.
Имя интерфейсов, чаще всего отглагольные существительные - Storager.
Надо постараться, чтобы объявленный интерфейс, не изменялся дальше по мере дописывания нового кода.

2024-10-07 17:25 UTC, rktkov commented on cmd/server/storage/storage.go
> +	val, err := ms.Gauges[name]
Неудачный выбор имени переменной, обычно ожидают увидеть ok при вызове словаря. А уже дальше если есть мысль считать это ошибкой, то тогда ее и определять.

2024-10-07 17:25 UTC, rktkov commented on cmd/server/handlers/server.go
> +	"github.com/go-chi/chi/v5"
import

Возьмите в привычку сортировать импортируемые пакеты следующим образом:
1. пакеты стандартной библиотеки
2. внешние установленные пакеты
3. внутренние пакеты проекта

Для того, чтобы разные автоматические инструменты их не пересортировывали, разделяйте блоки пустой строкой.

см. комментарий про порядок импорта
https://stackoverflow.com/questions/24790175/when-is-the-init-function-run

2024-10-07 17:25 UTC, rktkov commented on cmd/agent/handlers/request.go
> +package handlers
Применить правки согласно комментариям ниже.

2024-10-14 11:08 UTC, rktkov approved these changes

2024-10-14 11:08 UTC, rktkov commented on cmd/server/handlers/server/server.go
> +type MemStorager interface {
Вот это лишний, можно и нужно использовать Storager дальше.

2024-10-14 11:12 UTC, ramil063 commented on cmd/server/handlers/server/server.go
> +type MemStorager interface {
ты вроде говорил что мы будем дальше использовать базу данных. я думал чтобы легко переключаться между местами хранения будет DBStorager и MemStorager а может еще будет и какой нибудь FileStorager.
я загнался наверное.
ничего плохого не будет если я поправлю после апрува?

2024-10-14 14:44 UTC, merged